### ISSUE TITLE
wrong id in createPlugin function

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/plugin-i18next#2]
## Problem

the id mentions "samuelstroschein.inlangPluginJson"

## Solution

Rename it to "inlang.plugin-i18next" or something.

**Comment by samuelstroschein** [comment]
fixed by [a582be1](https://github.com/inlang/plugin-i18next/commit/a582be1f5c69fbeeffc426f8f26eb92ddf87f1c8)
